### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by ssokolow** [ShatReal/pixel-art-converter#1]
Without an explicit license declaration, the interaction between "All Rights Reserved" and GitHub's Terms of Service basically means that people are allowed to view the code on GitHub and fork and edit it using GitHub's built-in editors, but not to download and run it.

https://choosealicense.com/ is the simplest way to fix that. Just find the license you want and there's a button to auto-generate a pull request to add the license file.

**Comment by ShatReal** [comment]
I have added a license file.
